로그인 mvvm 패턴으로 자동로그인
f-lab-edu/danggn-clone-refactor-android pull request #18
Opened 2024-07-04 14:25 UTC by sszz07

1.LocalDB
2.UserViewModel
3.SplashActivity

LocalDB클래스에서 로컬로 저장되어있는 폰넘버 데이터를 읽어옴 -> LoginUserChekingDB 비즈니스 로직을 처리하고 -> UserViewModel에서 기존에 존재하는 폰넘버이면 메인페이지로 인텐트 하고 존재하지 않으면 회원가입 페이지로 이동한다

2024-07-07 12:57 UTC, f-lab-terry requested changes

2024-07-07 12:57 UTC, f-lab-terry commented on app/src/main/AndroidManifest.xml
> +<<<<<<< Updated upstream
빌드 되나요?

2024-07-07 12:57 UTC, f-lab-terry commented on app/src/main/java/com/example/freemarket/dto/ProductDto.kt
> +//이게 뭐길래 있어야 돼?
없어도 됩니다.

2024-07-07 12:57 UTC, f-lab-terry commented on app/src/main/java/com/example/test/PhoneActivity.kt
> +            number = "+821055890048"
번호가 왜 하드코딩 되어 있나요?

2024-07-08 06:32 UTC, sszz07 commented on app/src/main/java/com/example/test/PhoneActivity.kt
> +            number = "+821055890048"
번호 입력안하고 빠르게 기능 확인하려고 하드코딩 했었습니다 수정할께요

2024-07-08 06:32 UTC, sszz07 commented on app/src/main/java/com/example/freemarket/dto/ProductDto.kt
> +//이게 뭐길래 있어야 돼?
나중에 공부하려고 주석 해놓은건데 브랜치 올릴때 체크하겠습니다

2024-07-08 06:33 UTC, sszz07 commented on app/src/main/AndroidManifest.xml
> +<<<<<<< Updated upstream
프로젝트랑 깃헙 데스크가 원격으로 연결이 되어있어서 생긴 문제라고 합니다 브랜치 올릴때 체킹하겠습니다

2024-07-09 12:31 UTC, sszz07 reviewed
충돌 수정

2024-07-10 01:02 UTC, merged